### ISSUE TITLE
logging camp allows all recipies for assembling machine

### ISSUE THREAD

**Issue by mmarvo** [mspielberg/Xander-Mod#3]
prototypes/entity/production/miner.lua:         crafting_categories = {"temp-logging"},

that line does not replace the crafting categories for logging camp cloned from
xmutil.clone("assembling-machine", "assembling-machine-2",

because clone function in xmutil.lua merges anything that is a table
first thought was to make the category a string but it requires list or dict, could bodge it somehow but you probably have a better way :)

**Comment by mspielberg** [comment]
Fixed in v2.2.3.
