### ISSUE TITLE
standard belts not available to craft

### ISSUE THREAD

**Issue by mmarvo** [mspielberg/Xander-Mod#5]
even with the fix to unlock the recipe standard belts are not available
guess that it is to do with crafting category or possibly (and better / worse) it is some cacheing issue which I have had before  

the category looks ok 
data.raw.recipe["transport-belt"].category = "crafting" in  prototypes\recipe\production\production.lua
testing it from scratch is 20hrs gametime :/ maybe there is a better way?

**Comment by mspielberg** [comment]
Fixed in v2.2.3.
